import test from 'node:test';import assert from 'node:assert/strict';
import users from '../api/users.js';import tasks from '../api/tasks.js';import auth from '../api/auth.js';import digest from '../api/digest.js';
const uid='11111111-1111-4111-8111-111111111111';
process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_example';process.env.SUPABASE_SECRET_KEY='sb_secret_example';process.env.APP_URL='https://focusdesk.example';
function response(){return{headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},json(v){this.data=v;return this}};}
const req=(method,body)=>({method,body,query:{},headers:{cookie:'fd_access=valid',origin:'https://focusdesk.example','content-type':'application/json'}});
function fakeFetch(profile,calls){return async(url,opts)=>{calls.push({url,opts});if(url.endsWith('/auth/v1/user'))return new Response(JSON.stringify({id:uid,email:'owner@example.com'}));if(url.includes('grant_type=password'))return new Response(JSON.stringify({access_token:'sensitive-access',refresh_token:'sensitive-refresh',expires_in:3600,user:{id:uid}}));if(url.includes('/fd_profiles?'))return new Response(JSON.stringify([profile]));throw Error('Unexpected downstream call: '+url)}}
test('API users denies normal user before any admin Auth API',async()=>{const prior=global.fetch,calls=[];global.fetch=fakeFetch({id:uid,role:'user',is_active:true},calls);try{const r=response();await users(req('POST',{action:'invite',email:'x@example.com',display_name:'X'}),r);assert.equal(r.code,403);assert.equal(calls.length,2);assert.ok(!calls.some(c=>c.opts.headers.apikey==='sb_secret_example'))}finally{global.fetch=prior}});
test('inactive session cannot retrieve task data',async()=>{const prior=global.fetch,calls=[];global.fetch=fakeFetch({id:uid,role:'user',is_active:false},calls);try{const r=response();await tasks(req('GET'),r);assert.equal(r.code,403);assert.equal(calls.length,2)}finally{global.fetch=prior}});
test('successful login returns HttpOnly cookies, never token JSON',async()=>{const prior=global.fetch,calls=[];global.fetch=fakeFetch({id:uid,role:'admin',is_active:true,email:'owner@example.com'},calls);try{const r=response();await auth(req('POST',{action:'login',email:'owner@example.com',password:'a-valid-password'}),r);assert.equal(r.code,200);assert.equal(r.headers['Set-Cookie'].length,2);assert.ok(r.headers['Set-Cookie'].every(c=>c.includes('HttpOnly; Secure; SameSite=Lax')));assert.ok(!JSON.stringify(r.data).includes('sensitive'));assert.equal(r.headers['Cache-Control'],'no-store')}finally{global.fetch=prior}});
test('cross-origin login and anonymous cron fail closed',async()=>{const r=response(),q=req('POST',{action:'login'});q.headers.origin='https://attacker.example';await auth(q,r);assert.equal(r.code,403);const d=response();await digest({method:'GET',headers:{},query:{}},d);assert.equal(d.code,401)});
