import test from 'node:test';import assert from 'node:assert/strict';import ExcelJS from 'exceljs';
import {reportFilters,summarize,csvCell,csvReport} from '../server/report.js';import {workbookReport} from '../server/report-workbook.js';import {assignmentMessage} from '../server/assignment-email.js';import {conflicts} from '../public/js/model.js';import assignments from '../api/assignments.js';import tasks from '../api/tasks.js';
const uid='11111111-1111-4111-8111-111111111111',dev='22222222-2222-4222-8222-222222222222';
const task={id:uid,user_id:uid,title:'=HYPERLINK("https://example.com")',category:'Full Time',project:'Project, A',kind:'Delivery',owner_name:'Owner',owner_email:'owner@example.com',pic_id:dev,assignee_id:dev,pic_name:'Programmer',pic_email:'dev@example.com',priority:'High',status:'Done',due_date:'2026-09-10',scheduled_date:'2026-09-09',start_time:'09:00',duration:90,completed_at:'2026-09-09T17:30:00Z',progress_note:'Ready\nfor UAT',notes:'Scope',version:3};
const report={filters:reportFilters({month:'2026-09'}),generatedAt:'2026-10-01T01:00:00Z',generatedDay:'2026-10-01',owner:'Owner',rows:[task,{...task,id:dev,title:'Review',status:'In progress',duration:30,completed_at:null}],summary:null};report.summary=summarize(report.rows,report.generatedDay);
test('report months roll over and filters reject malformed values',()=>{assert.equal(reportFilters({month:'2026-12'}).end,'2027-01-01');assert.equal(reportFilters({month:'2024-02'}).end,'2024-03-01');for(const q of [{month:'2026-13'},{basis:'created'},{scope:'everyone'},{pic:'bad'},{category:'private'}])assert.throws(()=>reportFilters(q))});
test('summary uses current statuses, estimates and overdue at export',()=>{assert.equal(report.summary.total,2);assert.equal(report.summary.done,1);assert.equal(report.summary.minutes,120);assert.equal(report.summary.overdueNow,1);assert.equal(report.summary.byPic[0].tasks,2)});
test('CSV prevents formula execution and preserves commas/newlines',()=>{for(const s of ['=1+1',' +SUM(A1)','-1','@SUM(A1)','\t=1','\ntext'])assert.ok(csvCell(s).startsWith('"\''));assert.equal(csvCell(90),'90');const csv=csvReport(report);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes('"Project, A"'));assert.ok(csv.includes('"Ready\nfor UAT"'));assert.ok(csv.includes('"Report month"'));assert.ok(csv.includes('2026-09-10 00:30:00'))});
test('XLSX roundtrip keeps untrusted text literal, dates typed, numeric estimates and formula results',async()=>{const data=await workbookReport(report);const w=new ExcelJS.Workbook();await w.xlsx.load(data);assert.deepEqual(w.worksheets.map(s=>s.name),['Summary','Tasks']);const t=w.getWorksheet('Tasks');assert.equal(t.rowCount,3);assert.equal(t.getCell('B2').value,task.title);assert.equal(t.getCell('B2').type,ExcelJS.ValueType.String);assert.equal(t.getCell('O2').value,90);assert.ok(t.getCell('L2').value instanceof Date);assert.equal(t.getCell('P2').value.toISOString(),'2026-09-10T00:30:00.000Z');const rows=[];w.getWorksheet('Summary').eachRow(r=>rows.push(r.values));const hours=rows.find(r=>r[1]==='Estimated hours');assert.equal(hours[2].result,2);const done=rows.find(r=>r[1]==='Current status: Done');assert.equal(done[2].result,1);assert.equal(t.views[0].state,'frozen')});
test('empty XLSX has valid headers, summary zero and no reversed formulas',async()=>{const r={...report,rows:[],summary:summarize([])};const w=new ExcelJS.Workbook();await w.xlsx.load(await workbookReport(r));assert.equal(w.getWorksheet('Tasks').rowCount,1);assert.equal(w.getWorksheet('Summary').getCell('B13').value,0)});
test('assignment preview names trusted PIC and scoped link; email-only gets reply workflow',()=>{const m=assignmentMessage(task,'https://focusdesk.example');assert.ok(m.text.includes('dev@example.com')||m.recipient==='dev@example.com');assert.ok(m.text.includes('?task='+uid));assert.ok(m.text.includes('Scope'));const external=assignmentMessage({...task,assignee_id:null},'https://focusdesk.example');assert.ok(!external.text.includes('?task='));assert.ok(external.text.includes('owner@example.com'))});
test('overlap warnings compare executor, not unrelated delegated schedules',()=>{assert.equal(conflicts(task,[{...task,id:'other',assignee_id:'someone'}]).length,0);assert.equal(conflicts({...task,status:'To do'},[{...task,id:'other',status:'To do'}]).length,1);assert.equal(conflicts({...task,status:'To do'},[{...task,id:'other',status:'To do',start_time:'10:30'}]).length,0)});
process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_example';process.env.SUPABASE_SECRET_KEY='sb_secret_example';process.env.APP_URL='https://focusdesk.example';process.env.RESEND_API_KEY='mock';process.env.EMAIL_FROM='Focusdesk <noreply@example.com>';
const req=(method,body)=>({method,body,query:{},headers:{cookie:'fd_access=valid',origin:'https://focusdesk.example','content-type':'application/json'}});
function response(){return{headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},json(v){this.data=v;return this}}}
function authFetch(next){return async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return new Response(JSON.stringify({id:uid}));if(url.includes('/fd_profiles?'))return new Response(JSON.stringify([{id:uid,is_active:true,role:'user'}]));return next(url,opts)}}
test('email POST ignores spoofed recipient and uses claimed snapshot/idempotency key',async()=>{const before=fetch;let sent;global.fetch=authFetch(async(url,opts)=>{if(url.includes('/rpc/fd_prepare_assignment'))return new Response(JSON.stringify({claimed:true,message:{id:dev,recipient_email:'dev@example.com',payload:task}}));if(url==='https://api.resend.com/emails'){sent={body:JSON.parse(opts.body),headers:opts.headers};return new Response('{"id":"mock-id"}')};if(url.includes('/fd_assignment_messages?'))return new Response(null,{status:204});throw Error('Unexpected '+url)});try{const r=response();await assignments(req('POST',{task_id:uid,version:3,recipient:'attacker@example.com'}),r);assert.equal(r.code,200);assert.deepEqual(sent.body.to,['dev@example.com']);assert.equal(sent.body.reply_to,'owner@example.com');assert.equal(sent.headers['Idempotency-Key'],'fd-assignment-'+dev)}finally{global.fetch=before}});
test('duplicate assignment stops before provider request',async()=>{const before=fetch;let provider=0;global.fetch=authFetch(async(url)=>{if(url.includes('/rpc/fd_prepare_assignment'))return new Response('{"claimed":false,"message":{"status":"accepted"}}');provider++;throw Error('Unexpected '+url)});try{const r=response();await assignments(req('POST',{task_id:uid,version:3}),r);assert.equal(r.code,200);assert.equal(provider,0)}finally{global.fetch=before}});
test('assignee API rejects full edits and only forwards progress fields',async()=>{const before=fetch;let written;global.fetch=authFetch(async(url,opts)=>{if(url.includes('/fd_tasks?')){if(opts.method==='PATCH'){written=JSON.parse(opts.body);return new Response(JSON.stringify([task]))}return new Response(JSON.stringify([{...task,user_id:dev,assignee_id:uid}]))}throw Error('Unexpected '+url)});try{const bad=response();await tasks(req('PATCH',{id:uid,version:3,title:'Attempt'}),bad);assert.equal(bad.code,403);assert.equal(written,undefined);const ok=response();await tasks(req('PATCH',{id:uid,version:3,action:'progress',status:'Done',progress_note:'Ready',title:'Attempt'}),ok);assert.equal(ok.code,200);assert.deepEqual(written,{status:'Done',progress_note:'Ready'})}finally{global.fetch=before}});
