import {timingSafeEqual} from 'node:crypto';
export class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
export function env(){const url=(process.env.SUPABASE_URL||'').replace(/\/$/,'');const key=process.env.SUPABASE_PUBLISHABLE_KEY||'';const app=(process.env.APP_URL||'').replace(/\/$/,'');if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(url)||!key||!/^https:\/\//.test(app))throw new HttpError(503,'Konfigurasi server belum lengkap. Periksa SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, dan APP_URL.');if(key.startsWith('sb_secret_'))throw new HttpError(503,'SUPABASE_PUBLISHABLE_KEY tidak boleh berisi secret key.');return{url,key,app};}
export function reply(res,status,data){res.setHeader('Cache-Control','no-store');res.setHeader('Vercel-CDN-Cache-Control','no-store');return res.status(status).json(data);}
export function mutation(req){const {app}=env();if(!['POST','PATCH','DELETE'].includes(req.method))throw new HttpError(405,'Method not allowed');if(req.headers.origin!==new URL(app).origin)throw new HttpError(403,'Origin tidak diizinkan. Pastikan APP_URL sama dengan alamat aplikasi ini.');if(req.headers['content-type']?.split(';')[0]!=='application/json')throw new HttpError(415,'JSON required');}
export function body(req,maxBytes=20000){if(Number(req.headers['content-length']||0)>maxBytes)throw new HttpError(413,'Request too large');let b=req.body;try{if(typeof b==='string')b=JSON.parse(b)}catch{throw new HttpError(400,'JSON invalid');}if(!b||typeof b!=='object'||Array.isArray(b)||JSON.stringify(b).length>maxBytes)throw new HttpError(400,'Invalid request');return b;}
export async function sb(path,{method='GET',data,token,admin=false,headers={}}={}){const c=env();const key=admin?process.env.SUPABASE_SECRET_KEY:c.key;if(!key)throw new HttpError(503,'SUPABASE_SECRET_KEY belum dikonfigurasi untuk tindakan admin.');const bearer=token||(key.startsWith('eyJ')?key:null);const h={apikey:key,'Content-Type':'application/json',...(bearer?{Authorization:'Bearer '+bearer}:{}),...headers};let r;try{r=await fetch(c.url+path,{method,headers:h,body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(15000)});}catch{throw new HttpError(502,'Supabase tidak dapat dijangkau. Coba kembali.');}const text=await r.text();let value;try{value=text?JSON.parse(text):null}catch{throw new HttpError(502,'Respons Supabase tidak valid.');}if(!r.ok)throw new HttpError(r.status>=500?502:r.status,value?.msg||value?.message||value?.error_description||'Permintaan Supabase gagal');return value;}
export function cookies(req){const out={};for(const part of (req.headers.cookie||'').split(';')){const i=part.indexOf('=');if(i>0){try{out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1))}catch{}}}return out;}
export function setSession(res,s){const make=(k,v,age)=>`${k}=${encodeURIComponent(v)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${age}`;res.setHeader('Set-Cookie',[make('fd_access',s.access_token,Math.min(s.expires_in||3600,3600)),make('fd_refresh',s.refresh_token,604800)]);}
export function clearSession(res){res.setHeader('Set-Cookie',['fd_access=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0','fd_refresh=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0']);}
export async function identity(req,res,{active=true}={}){const c=cookies(req);let token=c.fd_access,user;try{if(!token)throw new HttpError(401,'No session');user=await sb('/auth/v1/user',{token});}catch(e){if(e.status!==401&&e.status!==403)throw e;if(!c.fd_refresh)throw new HttpError(401,'Silakan masuk.');try{const s=await sb('/auth/v1/token?grant_type=refresh_token',{method:'POST',data:{refresh_token:c.fd_refresh}});token=s.access_token;setSession(res,s);user=await sb('/auth/v1/user',{token});}catch{clearSession(res);throw new HttpError(401,'Sesi berakhir. Silakan masuk kembali.');}}
 const rows=await sb('/rest/v1/fd_profiles?id=eq.'+user.id+'&select=*',{token});const profile=rows[0];if(!profile)throw new HttpError(403,'Profil belum tersedia. Jalankan SQL setup.');if(active&&!profile.is_active)throw new HttpError(403,'Akun belum aktif atau dinonaktifkan. Hubungi admin.');return {token,user,profile};}
export async function adminIdentity(req,res){const ctx=await identity(req,res);if(ctx.profile.role!=='admin')throw new HttpError(403,'Hanya admin yang dapat mengelola pengguna.');return ctx;}
export function uuid(v){if(typeof v!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v))throw new HttpError(400,'Invalid ID');return v;}
export function email(v){if(typeof v!=='string'||v.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))throw new HttpError(400,'Email tidak valid');return v.trim().toLowerCase();}
export function password(v){if(typeof v!=='string'||v.length<12||v.length>128)throw new HttpError(400,'Gunakan password 12–128 karakter.');return v;}
export function secretMatches(a,b){if(!a||!b||b.length<32)return false;const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
export function handler(fn){return async(req,res)=>{try{return await fn(req,res)}catch(e){return reply(res,e.status||500,{error:e.status?e.message:'Terjadi kesalahan server. Coba lagi.'})}};}
