import {readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite();
await db.exec(`create schema auth;create role anon;create role authenticated;create role service_role bypassrls;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb not null default '{}'::jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon,service_role;`);
for(const f of ['01_schema.sql','03_pic_reports.sql','04_recurring_tasks.sql','05_telegram_workflow.sql','07_telegram_sync_pic.sql','08_scheduled_briefings.sql','10_knowledge_desk.sql','10_knowledge_desk.sql'])await db.exec(await readFile('supabase/'+f,'utf8'));
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333';const one=async(s,p=[])=>(await db.query(s,p)).rows[0];
await db.query(`insert into auth.users(id,email) values($1,'owner@example.com'),($2,'dev@example.com'),($3,'other@example.com')`,[A,B,C]);await db.exec("update fd_profiles set is_active=true;update fd_profiles set role='admin' where email<>'dev@example.com'");
async function user(id,fn){await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);try{return await fn()}finally{await db.exec("reset role;select set_config('request.jwt.claim.sub','',false)")}}
async function service(fn){await db.exec('set role service_role');try{return await fn()}finally{await db.exec('reset role')}}
const master=(kind,d={},u=A)=>user(u,()=>one('select fd_desk_admin($1,$2::jsonb) result',[kind,JSON.stringify(d)]));
await master('seed');await master('seed');assert.equal((await one('select count(*)::int n from fd_desk_priorities')).n,4);await assert.rejects(()=>master('seed',{},B),/Admin/);
await db.query('insert into fd_telegram_accounts(user_id,telegram_id,chat_id) values($1,101,101),($2,202,202)',[A,B]);
const pic=(await user(A,()=>one(`select (fd_save_pic(gen_random_uuid(),'Developer','dev@example.com',true,true)).id id`))).id;
const G=(await one("insert into fd_telegram_groups(owner_id,chat_id,title) values($1,-100,'GEE support') returning id",[A])).id;const H=(await one("insert into fd_telegram_groups(owner_id,chat_id,title) values($1,-200,'Other support') returning id",[C])).id;
const priority=(await one("select id from fd_desk_priorities where name='High'")).id,category=(await one("select id from fd_desk_categories where name='Bug'")).id;
const data={code:'GEE',name:'GEE Platform',description:'test',work_area:'Full Time',default_pic_id:pic,priority_id:priority,requires_testing:true,active:true};const app=(await master('application',data)).result.id;
await assert.rejects(()=>master('application',{...data,id:app},C),/workspace/);await assert.rejects(()=>master('binding',{application_id:app,group_id:H,active:true}),/workspace/);await master('binding',{application_id:app,group_id:G,active:true});
const route=(await master('route',{application_id:app,category_id:category,priority_id:priority,pic_id:pic,active:true})).result.id;
const art={application_id:app,title:'Preset Guide',keywords:'preset filter',content_md:'# Preset\nContoh untuk pengujian.',status:'Draft',chunks:[{heading:'Preset filter',content:'Gunakan panduan aplikasi untuk preset filter.',position:0}]};const article=(await master('article',art)).result.id;
const search=()=>service(()=>one('select fd_desk_search($1,-100,$2) result',[app,['preset','filter']]));assert.equal((await search()).result.length,0);await master('article',{...art,id:article,status:'Published'});assert.equal((await search()).result.length,1);assert.equal((await service(()=>one('select fd_desk_search($1,-200,$2) result',[app,['preset','filter']]))).result.length,0);
const ask=(upd=1)=>service(()=>one('select fd_desk_ask($1,-100,11,999,\'Reporter\',$2,\'Gimana preset filter?\',$3) id',[upd,app,['preset','filter']]));const r=(await ask()).id;assert.equal((await ask()).id,r);assert.equal((await one('select status from fd_support_requests where id=$1',[r])).status,'Answered');
assert.equal((await service(()=>db.query('select * from fd_desk_claim(8)'))).rows.length,1);await db.query("update fd_desk_outbox set status='sent',sent_message_id=22 where request_id=$1",[r]);
const action=(upd,act,value=null,who=999)=>service(()=>one('select fd_desk_action($1,-100,22,$2,$3,$4,$5) result',[upd,who,r,act,value]));await assert.rejects(()=>action(2,'escalate',null,998),/pelapor/);await action(2,'escalate');await action(3,'c'+route.slice(0,8));await action(4,'confirm');await action(4,'confirm');await action(5,'confirm');assert.equal((await one('select count(*)::int n from fd_tasks')).n,1);
const report=await one('select * from fd_support_requests where id=$1',[r]),task=await one('select * from fd_tasks where id=$1',[report.task_id]);assert.equal(task.assignee_id,B);assert.equal(task.user_id,A);assert.equal(task.requires_testing,true);assert.equal(report.priority_name,'High');
await assert.rejects(()=>service(()=>db.query("update fd_support_requests set question='changed' where id=$1",[r])),/terkunci/);await assert.rejects(()=>user(B,()=>db.query("update fd_support_requests set status='Resolved' where id=$1",[r])),/permission denied/);await assert.rejects(()=>user(A,()=>db.query("delete from fd_support_requests where id=$1",[r])),/permission denied/);assert.equal((await user(C,()=>db.query('select * from fd_support_requests'))).rows.length,0);assert.equal((await user(B,()=>db.query('select * from fd_support_requests'))).rows.length,1);
await action(6,'note','Koreksi: filter tidak tersimpan.');assert.equal((await one('select question from fd_support_requests where id=$1',[r])).question,'Gimana preset filter?');await assert.rejects(()=>service(()=>db.query("update fd_support_notes set content='changed'")),/append-only/);
await user(B,()=>db.query("update fd_tasks set status='In progress' where id=$1",[task.id]));assert.ok((await one("select count(*)::int n from fd_desk_outbox where dedupe_key like 'status:%'")).n>0);await user(B,()=>db.query("update fd_tasks set status='Ready for Testing' where id=$1",[task.id]));await assert.rejects(()=>user(B,()=>db.query("update fd_tasks set status='Done' where id=$1",[task.id])));await user(A,()=>db.query("update fd_tasks set status='Testing' where id=$1",[task.id]));await user(A,()=>db.query("update fd_tasks set status='Done' where id=$1",[task.id]));assert.equal((await one('select status from fd_support_requests where id=$1',[r])).status,'Resolved');
for(const row of (await db.query('select markup from fd_desk_outbox where markup is not null')).rows)for(const bs of row.markup.inline_keyboard||[])for(const b of bs)assert.ok(Buffer.byteLength(b.callback_data)<=64,b.callback_data);
await db.query('update fd_desk_groups set active=false where group_id=$1',[G]);await assert.rejects(()=>action(7,'status'),/aktif/);await assert.rejects(()=>user(A,()=>db.query('select fd_desk_claim(8)')),/permission denied/);
await db.close();console.log('PASS v1.6 SQL: migration replay, isolation, search, immutability, authorization, idempotency, PIC/review workflow, callback limit, revoked access.');
