import {readFile} from 'node:fs/promises';import assert from 'node:assert/strict';import unzipper from 'unzipper';import {resolve} from 'node:path';
const folder=resolve(process.argv[2]||'../focusdesk-v1_6-release');const archive=await unzipper.Open.file(folder+'/Focusdesk_Vercel_v1_6.zip');const names=archive.files.map(f=>f.path);
for(const f of ['README.md','package.json','api/desk.js','server/desk.js','server/knowledge.js','public/desk.html','public/guide-v1-6.html','supabase/10_knowledge_desk.sql','supabase/11_diagnostics.sql','Focusdesk_v1_5_to_v1_6.sql','Focusdesk_Activate_Scheduler_v1_6.sql','Focusdesk_Upgrade_to_v1_6.sql','Focusdesk_Supabase_v1_6.sql','docs/KNOWLEDGE_DESK.md'])assert.ok(names.includes(f),f);
assert.ok(!names.some(n=>/(^|\/)(node_modules|dist|\.git|qa)\//.test(n)));assert.ok(!names.includes('.env'));assert.ok(!names.includes('.env.local'));
assert.equal(JSON.parse((await archive.files.find(f=>f.path==='package.json').buffer()).toString()).version,'1.6.0');
const lock=JSON.parse((await archive.files.find(f=>f.path==='package-lock.json').buffer()).toString());assert.equal(lock.version,'1.6.0');assert.equal(lock.packages[''].version,'1.6.0');
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite();await db.exec(`create schema auth;create role anon;create role authenticated;create role service_role bypassrls;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb not null default '{}'::jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon,service_role;`);
for(const f of ['Focusdesk_Supabase_v1_6.sql','Focusdesk_Upgrade_to_v1_6.sql','Focusdesk_v1_5_to_v1_6.sql']){const sql=(await archive.files.find(x=>x.path===f).buffer()).toString();assert.equal(sql,await readFile(folder+'/'+f,'utf8'));assert.equal((sql.match(/^begin;$/gm)||[]).length,1);assert.equal((sql.match(/^commit;$/gm)||[]).length,1);assert.ok(!sql.includes('cron.schedule('));await db.exec(sql);}
await db.close();console.log('PASS v1.6 release: filenames, version, no secrets/dependencies, SQL bytes match, fresh + full upgrade + incremental replay, single transactions.');
